project:
  type: website
  output-dir: docs

filters:
- nceas-learning-hub/lh_theme
editor: source
# bibliography: book.bib

format:
  html:
    theme: ### can only point to scss, not css
       light: _extensions/nceas-learning-hub/lh_theme/lh_light.scss
       dark: _extensions/nceas-learning-hub/lh_theme/lh_dark.scss
    css: _extensions/nceas-learning-hub/lh_theme/lh_style.css   ### doesn't render NCEAS logo if put in scss file?
    toc: true
    number-sections: true
    title-block-banner: "#00000044" ### need something here to "turn on" the title-block-banner


website:
  title: "coreR_test2 (2024-01-01 - 2024-12-31)"
  reader-mode: false
  repo-url: https://github.com/nceas-learning-hub/coreR_test2

  favicon: _extensions/nceas-learning-hub/lh_theme/logo_lh_hex.png # learning hub logo on browser tab

  bread-crumbs: false
  navbar:
    right:
      - text: "Instructors"
        menu:
          - text: "Casey O'Hara"
            href: https://www.oharascience.com/
      - icon: github
        href: https://github.com/nceas-learning-hub/coreR_test2
        aria-label: GitHub

  sidebar:
    title: "Training Materials"
    style: "floating"
    search: true
    tools:
      - icon: house-door-fill
        href: https://www.nceas.ucsb.edu/learning-hub
      - icon: twitter
        href: https://twitter.com/ucsb_nceas
      - icon: github
        href: COURSE_URL
    contents:
      - index.qmd # preface
      - s01_github_introduction.qmd  ###  (coreRlessons version 2024.11.07)

  page-footer:
    center: "Copyright \u00a9 2024, NCEAS"
    ### NCEAS main website footer:
    # center: "\u00a9 The Regents of the University of California, All Rights Reserved"
    # could also include license info?


